<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta charset="utf-8">
    <title>Marvel Characters</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">

	<!-- Hosted Bootstrap 4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
    
    <!-- site specific styling -->
    <link rel="stylesheet" href="./css/styles.css" />
    
    <!-- font awesome -->
    <link href="./font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    <!-- jQuery DataTable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css" />
    
</head>
<body class="bg-faded">
 
<nav id="topNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <button class="navbar-toggler hidden-md-up pull-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
            ☰
        </button>

        <a class="navbar-brand page-scroll" href="index.jsp">Marvel Super Characters</a>

        <div class="collapse navbar-toggleable-sm" id="collapsingNavbar">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="index.jsp#one">Search Tool</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="add.do">Add Character</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="GetAllCharactersData.do?">Get All</a>
                </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
                <li class="nav-item">
                    <a class="nav-link page-scroll" data-toggle="modal" href="#aboutModal">About</a>
                </li>
            </ul>
        </div>
    </div><!-- .container -->
</nav>

<c:choose>
	<c:when test="${!empty character}">
	</c:when>
	<c:otherwise>
 		<header id="first">
 			<img class="img-responsive" id="headerImg" src="./img/smHeadShotCollage.jpg" usemap="#Map">
 				<map name="Map" id="Map">
				    <area alt="" title="" href="GetCharacterData.do?characterName=Iron Patriot" shape="poly" coords="38,3,147,2,148,148,40,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Colossus" shape="poly" coords="150,2,260,1,262,149,152,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Spider-Man" shape="poly" coords="263,1,375,1,374,149,264,148" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Scarlet Witch" shape="poly" coords="378,2,487,1,487,148,377,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Wolverine" shape="poly" coords="488,3,600,1,600,149,489,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Vision" shape="poly" coords="602,2,713,2,713,149,602,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Gambit" shape="poly" coords="715,2,825,1,826,148,716,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Beast" shape="poly" coords="827,0,938,1,938,149,828,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Archangel" shape="poly" coords="942,2,1051,2,1051,149,940,150" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Ant-Man" shape="poly" coords="1054,2,1164,1,1164,149,1054,149" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Jubilee" shape="poly" coords="39,152,149,152,149,300,38,300" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Wolverine" shape="poly" coords="152,151,262,151,262,301,151,300" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Cyber" shape="poly" coords="264,151,375,151,375,300,264,300" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Cable" shape="poly" coords="378,152,486,152,487,300,377,300" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Mysterio" shape="poly" coords="490,152,599,151,600,298,489,299" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Doctor Strange" shape="poly" coords="601,151,712,151,713,300,602,300" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Hawkeye" shape="poly" coords="715,152,825,152,826,299,715,299" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Eddie Brock" shape="poly" coords="828,151,938,152,938,299,828,298" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Cyclops" shape="poly" coords="942,152,1051,151,1051,299,940,299" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Captain America" shape="poly" coords="1053,151,1164,151,1162,299,1053,300" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Kraven" shape="poly" coords="38,302,150,303,150,450,38,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Spider-Man" shape="poly" coords="152,303,262,303,261,450,151,448" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Black Cat" shape="poly" coords="264,303,374,303,375,449,263,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Black Panther" shape="poly" coords="376,303,487,302,487,449,377,448" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Rogue" shape="poly" coords="491,302,599,301,600,449,489,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Nightcrawler" shape="poly" coords="603,303,713,303,712,449,603,448" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Bishop" shape="poly" coords="717,303,825,302,825,448,714,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Bullseye" shape="poly" coords="828,301,938,301,938,448,827,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Johnny Blaze" shape="poly" coords="940,301,1050,301,1051,449,940,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Hulk" shape="poly" coords="1053,303,1162,301,1163,449,1053,449" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Punisher" shape="poly" coords="38,451,149,452,149,599,38,598" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Norman Osborn" shape="poly" coords="152,451,263,451,263,598,151,600" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Magneto" shape="poly" coords="265,452,375,451,375,600,264,600" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Daredevil" shape="poly" coords="378,450,486,451,487,599,377,599" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Sentinels" shape="poly" coords="489,451,600,451,600,599,489,598" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Red Skull" shape="poly" coords="603,451,712,451,713,598,602,599" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Loki" shape="poly" coords="715,451,825,451,827,599,716,599" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Doctor Octopus" shape="poly" coords="828,451,938,451,938,599,829,599" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Luke Cage" shape="poly" coords="940,451,1051,451,1051,599,940,599" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Moon Knight" shape="poly" coords="1053,451,1164,452,1163,598,1053,599" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Mystique" shape="poly" coords="40,604,148,603,147,747,40,747" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Iron Man" shape="poly" coords="148,601,261,603,261,746,152,748" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Thor" shape="poly" coords="263,602,373,603,373,747,263,747" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Red Hulk" shape="poly" coords="375,604,486,602,486,747,377,747" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Danny Rand" shape="poly" coords="489,747,599,747,599,604,491,603" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Deadpool" shape="poly" coords="601,603,710,602,710,747,603,748" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Storm" shape="poly" coords="715,601,823,602,826,748,715,748" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Daredevil" shape="poly" coords="826,601,940,600,939,749,828,748" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Iron Man" shape="poly" coords="940,602,1050,601,1052,748,941,749" />
				    <area alt="" title="" href="GetCharacterData.do?characterName=Weapon X" shape="poly" coords="1052,601,1164,600,1164,748,1054,748" />
				</map>			
			</header>
		</c:otherwise>
	</c:choose>

<section id="one">
	<div class="container wow fadeInUp">
       	<h2>Marvel Super Characters</h2>
			<div class="card-group">
			<c:choose>
				<c:when test="${!empty character}">
		            <div class="card card-block text-xs-center">
		                <img class="img-fluid" src="${character.image}">
		            </div>
		            <div class="card card-block text-xs-center">
		                <h4 class="card-header">${character.name}</h4>
		                <div class="card-block text-xs-center">
							<h5 class="text-xs-center">Alias: ${character.alias}</h5>
							<h5 class="text-xs-center">Affiliation: ${character.affiliation}</h5>
							<h6 class="text-xs-center">Marvel ID: ${character.marvelId}</h6>
							<p class="text-xs-center">${character.desc}</p>
							</br>
							<a href="GoToUpdate.do?characterName=${character.name}"><button class="btn btn-md text-normal btn-danger" type="submit">Edit</button></a>
						</div>
						<div class="card-footer text-muted">
	                		<h5 class="text-xs-center">Toggle Through Characters</h5>
							<form action="navigate.do" method="GET">
								<button class="btn btn-md text-normal btn-primary-outline" type="submit" value="previous" name="previous">Previous</button>
								<button class="btn btn-md text-normal btn-primary-outline" type="submit" value="next" name="next">Next</button>
 							</form>
 						</div>
 						<div class="col-lg-12">
	                		<h5 class="text-xs-center">Get All Characters</h5>
							<form action="GetAllCharactersData.do" method="GET">
								<button class="btn btn-md text-normal btn-warning-outline" type="submit" value="">Get All</button>
 							</form>
 						</div>
		            </div>
				</c:when>
				<c:otherwise>
				<div class="card card-block text-xs-center">
					<img class="card-img-top img-fluid" src="./img/thanos.jpg" alt="Card image cap">
		            <div class="card card-block text-xs-center">
		                <h4 class="card-header">Search By Character Index</h4>
						<form action="GetCharacterData.do" method="GET">
							<fieldset>	
 								<input type="text" name="characterId" placeholder="Index">
 							</fieldset>
 							</br>
							<button class="btn btn-md text-normal btn-primary-outline" type="submit" value="Get Character Data">Submit</button>
 						</form>
		            </div>
		       	</div>
				<div class="card card-block text-xs-center">
					<img class="card-img-top img-fluid" src="./img/phoenix.png" alt="Card image cap">
		            <div class="card card-block text-xs-center">
		                <h4 class="card-header">Search By Character Name</h4>
						<form action="GetCharacterData.do" method="GET">
							<fieldset>	
 								<input type="text" name="characterName" placeholder="Name">
 							</fieldset>
 							</br>
							<button class="btn btn-md text-normal btn-primary-outline" type="submit" value="Get Character Data">Submit</button>
 						</form>
		            </div>
		       	</div>
		       	<div class="card card-block text-xs-center">
					<img class="card-img-top img-fluid" src="./img/venom.jpeg" alt="Card image cap">
		            <div class="card card-block text-xs-center">
		                <h4 class="card-header">Search By Character Alias</h4>
						<form action="GetCharacterData.do" method="GET">
							<fieldset>	
 								<input type="text" name="characterAlias" placeholder="Alias">
 							</fieldset>
 							</br>
							<button class="btn btn-md text-normal btn-primary-outline" type="submit" value="Get Character Data">Submit</button>
 						</form>
		            </div>
		       	</div>
				</c:otherwise>
			</c:choose>
        </div>
    </div>
</section>

<footer>
	<div class="row">
		<div class="col-lg-12">
			<p class="text-xs-center"><a href="http://www.chrisriouxdevelopment.com" target="_blank">Chris Rioux Development</a> &copy; 2016</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3" style="text-align:center">
			<a href="https://twitter.com/chrisrioux_" target="_blank"><i class="fa fa-twitter fa-2x"></i></a>&nbsp;&nbsp;
			<a href="https://www.linkedin.com/in/chris-rioux-b500569a" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a>&nbsp;&nbsp;
			<a href="https://github.com/chris-rioux" target="_blank"><i class="fa fa-github fa-2x"></i></a>
			</br>
      	</div>
	</div>
</footer>

<!-- Modals -->
<div id="aboutModal" class="modal fade" tabindex="-1" role="dialog"
		aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title text-xs-center">Full Stack Web Development</h4>
					<p class="text-xs-center">
						Check Out<a href="http://www.chrisriouxdevelopment.com"
							target="_blank"> ChrisRiouxDevelopment.com</a>
					</p>
					<div class="modal-body">
						<div class="row">
							<div class="col-xs-4 text-xs-center">
								<ul class="list-inline banner-social-buttons">
									<li id="topButton"><a href="https://twitter.com/chrisrioux_" target="_blank"
										class="btn btn-primary-outline"><i
										class="fa fa-twitter fa-fw"></i>&nbsp;&nbsp;Twitter</a></li><br> 
									<li><a href="https://github.com/chris-rioux" target="_blank"
										class="btn btn-primary-outline"><i
										class="fa fa-github-alt fa-fw"></i>&nbsp;&nbsp;Github</a></li><br>
									<li><a href="https://www.linkedin.com/in/chris-rioux-b500569a"
										target="_blank" class="btn btn-primary-outline"><i
										class="fa fa-linkedin-square fa-fw"></i>&nbsp;&nbsp;Linkedin</a></li><br>								
								</ul>
							</div>
							<div class="col-xs-8">
								<img class="center-block" src="./img/smallestPic.jpg" alt="">
							</div>
						</div>
						<hr>
						<div class="modal-footer">
							<button class="btn btn-primary center-block" data-dismiss="modal"
								aria-hidden="true">OK</button>
						</div><!-- /.modal-footer -->
					</div><!-- /.modal-body -->
				</div><!-- /.modal-header -->
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /#aboutModal -->

    <!--scripts loaded here-->    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
    
    <script src="js/scripts.js"></script>
    <script src="js/imageMapResizer.min.js"></script>
    
    <script>
    $(document).ready(function() {
    	$('Map').imageMapResize();
	});
    </script>
    
  </body>
</html>